### ISSUE TITLE
Make compile-tests.rkt RackUnit tests pass

### ISSUE THREAD

**Issue by kstrasser** [mgorlick/CRESTaceans#11]
Looks like the following need attention (and are not covered by other issues):
- letrec
- when
- unless
- or
- quasiquote
- macros
- call/cc

**Comment by mgorlick** [comment]
kstrasser wrote:

> Looks like the following need attention (and are not covered by other issues):
> - letrec
> - when
> - unless
> - or
> - quasiquote
> - macros
> - call/cc
> 
> when, unless, or, quasiquote, macros, and call/cc all were not properly 
> upgraded during the grand conversion to first-class binding environments.
> Non-hygienic macros are now just plain broken and I need to reintegrate 
> them with the internal macro processor that the compiler itself uses.
> All of the others are getting fixed now as I refactor the compiler.

Letrec should work (I think). Will you please send me the test cases 
that fail and their output?

**Comment by mgorlick** [comment]
The special forms when, unless, or, and call/cc were accidentally omitted in the compiler upgrade to binding environments as first-class constructions. Similarly, the code generation for quasiquotation does not conform to the new internal calling conventions for Motile closures.

Non-hygienic macros are still not properly integrated into the internal macro processor that the compiler now employs.

The special forms will be fixed in the next release of the compiler and I'm going to put off non-hygienic macros until I get the compiler stable again.

**Comment by mgorlick** [comment]
All of these issues are now resolved, with the exception of non-hygienic macros, with the release of the new compiler.
